"use client";
import Link from "next/link";
import { FormEvent, useState, useTransition } from "react";
import { updateClient } from "@/app/clients/actions";
import type { ClientDetail } from "@/lib/dashboard-types";
import { formatDate } from "@/lib/formatters";

const sources = [["in_person", "In person"], ["whatsapp", "WhatsApp"], ["website", "Website"], ["phone", "Phone"], ["imported", "Imported"], ["other", "Other"]];
const show = (value: string | null) => value ? formatDate(value) : "—";
export function ClientProfile({ initial }: { initial: ClientDetail }) {
  const [client, setClient] = useState(initial); const [consent, setConsent] = useState(client.marketing_opt_in); const [error, setError] = useState(""); const [saved, setSaved] = useState(false); const [pending, start] = useTransition();
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(""); setSaved(false); const data = new FormData(event.currentTarget); start(async () => { const result = await updateClient(client.id, { name: String(data.get("name")), phone: String(data.get("phone")), email: String(data.get("email") || "") || null, birthday: String(data.get("birthday") || "") || null, notes: String(data.get("notes") || "") || null, is_active: data.get("active") === "on", marketing_opt_in: consent, marketing_opt_in_source: consent && !client.marketing_opt_in ? String(data.get("source")) : client.marketing_opt_in_source }); if (!result.ok) setError(result.error); else { setClient(result.data); setSaved(true); } }); }
  return <div className="space-y-5"><form onSubmit={submit} className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="font-bold">Customer Information</h2>{error && <p className="mt-3 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}{saved && <p className="mt-3 rounded-lg bg-emerald-50 p-3 text-sm text-emerald-700">Client saved.</p>}<div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
    <label className="text-sm">Name<input required name="name" defaultValue={client.name} className="mt-1 w-full rounded-xl border p-2.5" /></label><label className="text-sm">Phone<input required name="phone" defaultValue={client.phone} className="mt-1 w-full rounded-xl border p-2.5" /></label><label className="text-sm">Email<input type="email" name="email" defaultValue={client.email || ""} className="mt-1 w-full rounded-xl border p-2.5" /></label><label className="text-sm">Birthday<input type="date" name="birthday" defaultValue={client.birthday || ""} className="mt-1 w-full rounded-xl border p-2.5" /></label><p className="text-sm text-slate-500">Customer since<br/><span className="text-slate-900">{show(client.created_at)}</span></p><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="active" defaultChecked={client.is_active}/> Active</label>
    <label className="sm:col-span-2 lg:col-span-3 text-sm">Internal Notes<textarea name="notes" defaultValue={client.notes || ""} rows={4} className="mt-1 w-full rounded-xl border p-2.5"/><span className="text-xs text-slate-500">Owner-only. Never included in customer-facing responses.</span></label>
  </div><div className="mt-5 border-t pt-5"><h3 className="font-bold">Marketing Preferences</h3><label className="mt-3 flex gap-2 text-sm"><input type="checkbox" checked={consent} onChange={(e) => setConsent(e.target.checked)}/> Customer agreed to receive WhatsApp promotions and special offers.</label>{consent && !client.marketing_opt_in && <label className="mt-3 block max-w-sm text-sm">Consent source<select required name="source" defaultValue="" className="mt-1 w-full rounded-xl border p-2.5"><option value="" disabled>Select source</option>{sources.map(([v,l]) => <option key={v} value={v}>{l}</option>)}</select></label>}<div className="mt-3 grid gap-2 text-sm text-slate-600 sm:grid-cols-3"><p>Consent date: {show(client.marketing_opt_in_at)}</p><p>Source: {client.marketing_opt_in_source?.replace("_", " ") || "—"}</p><p>Opt-out date: {show(client.marketing_opt_out_at)}</p></div></div><button disabled={pending} className="mt-5 rounded-xl bg-slate-950 px-5 py-2.5 font-semibold text-white disabled:opacity-50">{pending ? "Saving…" : "Save Changes"}</button></form>
  <section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{[["Total appointments", String(client.total_appointment_count)], ["Upcoming appointment", client.upcoming_appointment ? show(client.upcoming_appointment.start_at) : "—"], ["Last appointment", client.last_appointment ? show(client.last_appointment.start_at) : "—"], ["Last conversation", client.conversations[0] ? show(client.conversations[0].last_activity_at) : "—"], ["Last activity", show(client.last_activity_at)]].map(([label,value]) => <div key={label} className="rounded-2xl border bg-white p-4"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 font-semibold">{value}</p></div>)}</section>
  <section className="rounded-2xl border bg-white"><h2 className="border-b p-5 font-bold">Appointment History</h2>{client.appointments.length ? <div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left text-sm"><thead className="bg-slate-50"><tr><th className="p-4">Service</th><th className="p-4">Staff</th><th className="p-4">Date/time</th><th className="p-4">Status</th></tr></thead><tbody>{client.appointments.map((item) => <tr key={item.id} className="border-t"><td className="p-4">{item.service}</td><td className="p-4">{item.staff || "Unassigned"}</td><td className="p-4">{show(item.start_at)}</td><td className="p-4 capitalize">{item.status}</td></tr>)}</tbody></table></div> : <p className="p-8 text-center text-slate-500">No appointments yet.</p>}</section>
  <section className="rounded-2xl border bg-white"><h2 className="border-b p-5 font-bold">Conversation History</h2>{client.conversations.length ? <div className="divide-y">{client.conversations.map((item) => <Link key={item.id} href={`/conversation-center?conversation=${item.id}`} className="block p-5 hover:bg-slate-50"><div className="flex justify-between gap-4"><p className="font-medium">{item.last_message || "Conversation started"}</p><p className="whitespace-nowrap text-sm text-slate-500">{show(item.last_activity_at)}</p></div><p className="mt-1 text-xs text-slate-500">{item.message_count} messages · Open in Conversation Center</p></Link>)}</div> : <p className="p-8 text-center text-slate-500">No conversations yet.</p>}</section></div>;
}
