"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { FormEvent, useState, useTransition } from "react";
import { createClient } from "@/app/clients/actions";
import type { DashboardClient } from "@/lib/dashboard-types";
import { formatDate } from "@/lib/formatters";

const sources = [["in_person", "In person"], ["whatsapp", "WhatsApp"], ["website", "Website"], ["phone", "Phone"], ["imported", "Imported"], ["other", "Other"]];
export function ClientsManager({ clients, search, status }: { clients: DashboardClient[]; search: string; status: string }) {
  const router = useRouter(); const [open, setOpen] = useState(false); const [consent, setConsent] = useState(false); const [error, setError] = useState(""); const [pending, start] = useTransition();
  function filter(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); router.push(`/clients?search=${encodeURIComponent(String(data.get("search") || ""))}&status=${data.get("status") || "all"}`); }
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(""); const data = new FormData(event.currentTarget); start(async () => { const result = await createClient({ name: String(data.get("name")), phone: String(data.get("phone")), email: String(data.get("email") || "") || null, birthday: String(data.get("birthday") || "") || null, notes: String(data.get("notes") || "") || null, is_active: data.get("is_active") === "on", marketing_opt_in: consent, marketing_opt_in_source: consent ? String(data.get("source")) : null }); if (!result.ok) setError(result.error); else { setOpen(false); router.push(`/clients/${result.data.id}`); } }); }
  return <div className="space-y-5">
    <form onSubmit={filter} className="flex flex-col gap-3 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm sm:flex-row">
      <input name="search" defaultValue={search} aria-label="Search clients" placeholder="Search name or phone" className="min-w-0 flex-1 rounded-xl border border-slate-300 px-4 py-2.5" />
      <select name="status" defaultValue={status} aria-label="Client status" className="rounded-xl border border-slate-300 px-4 py-2.5"><option value="all">All clients</option><option value="active">Active</option><option value="inactive">Inactive</option><option value="opted_in">Opted in</option><option value="opted_out">Opted out</option><option value="never_booked">Never booked</option></select>
      <button className="rounded-xl bg-slate-200 px-5 py-2.5 font-semibold">Search</button><button type="button" onClick={() => setOpen(true)} className="rounded-xl bg-slate-950 px-5 py-2.5 font-semibold text-white">Add Client</button>
    </form>
    {open && <form onSubmit={submit} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex justify-between"><h2 className="text-lg font-bold">Add client</h2><button type="button" onClick={() => setOpen(false)}>Close</button></div>{error && <p className="mt-3 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="mt-4 grid gap-4 sm:grid-cols-2">
      <label className="text-sm font-medium">Name<input required name="name" className="mt-1 w-full rounded-xl border p-2.5" /></label><label className="text-sm font-medium">Phone<input required name="phone" className="mt-1 w-full rounded-xl border p-2.5" /></label><label className="text-sm font-medium">Email (optional)<input type="email" name="email" className="mt-1 w-full rounded-xl border p-2.5" /></label><label className="text-sm font-medium">Birthday (optional)<input type="date" name="birthday" className="mt-1 w-full rounded-xl border p-2.5" /></label><label className="sm:col-span-2 text-sm font-medium">Notes (private)<textarea name="notes" className="mt-1 w-full rounded-xl border p-2.5" /></label>
      <label className="flex gap-2 text-sm"><input type="checkbox" name="is_active" defaultChecked /> Active client</label><label className="flex gap-2 text-sm"><input type="checkbox" checked={consent} onChange={(e) => setConsent(e.target.checked)} /> Customer agreed to receive WhatsApp promotions and special offers.</label>{consent && <label className="text-sm font-medium">Consent source<select required name="source" defaultValue="" className="mt-1 w-full rounded-xl border p-2.5"><option value="" disabled>Select source</option>{sources.map(([v,l]) => <option key={v} value={v}>{l}</option>)}</select></label>}
    </div><button disabled={pending} className="mt-5 rounded-xl bg-slate-950 px-5 py-2.5 font-semibold text-white disabled:opacity-50">{pending ? "Saving…" : "Save Client"}</button></form>}
    {clients.length === 0 ? <div className="rounded-2xl border bg-white p-12 text-center"><p className="text-lg font-bold">No clients found</p><p className="mt-1 text-slate-500">Try another filter or add the first client.</p></div> : <div className="grid gap-3">{clients.map((client) => <Link key={client.id} href={`/clients/${client.id}`} className="grid gap-3 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm transition hover:border-slate-400 md:grid-cols-[1.3fr_1fr_1fr_auto]">
      <div><p className="font-bold">{client.name}</p><p className="text-sm text-slate-500">{client.phone}</p></div><div className="text-sm"><p className="text-slate-500">Last appointment</p><p>{client.last_appointment ? formatDate(client.last_appointment.start_at) : "Never"}</p></div><div className="text-sm"><p className="text-slate-500">Last activity</p><p>{client.last_activity_at ? formatDate(client.last_activity_at) : "No activity"}</p></div><div className="flex flex-wrap items-center gap-2 text-xs"><span className="rounded-full bg-slate-100 px-2 py-1">{client.total_appointment_count} appointments</span><span className={`rounded-full px-2 py-1 ${client.marketing_opt_in ? "bg-emerald-100 text-emerald-800" : "bg-slate-100"}`}>{client.marketing_opt_in ? "Opted in" : "Not opted in"}</span><span className="rounded-full bg-slate-100 px-2 py-1">{client.is_active ? "Active" : "Inactive"}</span></div>
    </Link>)}</div>}
  </div>;
}
