"use client";
/* eslint-disable @next/next/no-img-element -- campaign media uses owner-configured backend/object-storage URLs */

import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { cancelPromotion, deactivateCoupon, previewAudience, redeemCoupon, schedulePromotion, sendPromotion } from "@/app/promotions/actions";
import type { AudiencePreview, PromotionCampaign } from "@/lib/dashboard-types";

export function PromotionDetail({ campaign }: { campaign: PromotionCampaign }) {
  const router = useRouter(); const [pending, start] = useTransition(); const [error, setError] = useState(""); const [preview, setPreview] = useState<AudiencePreview | null>(null); const [schedule, setSchedule] = useState("");
  function act(work: ()=>Promise<{ok:boolean; data?:unknown; error?:string}>, confirm?: string) { if (confirm && !window.confirm(confirm)) return; setError(""); start(async()=>{const result=await work(); if(!result.ok)setError(result.error || "Action failed"); else router.refresh();}); }
  const counts = campaign.recipient_counts;
  return <div className="space-y-5">{error && <div className="rounded-xl bg-red-50 p-3 text-red-700">{error}</div>}
    <section className="grid gap-5 rounded-2xl border border-slate-200 bg-white p-5 lg:grid-cols-[1fr_240px]"><div><div className="flex items-center gap-3"><h2 className="text-xl font-bold">{campaign.name}</h2><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold capitalize">{campaign.status.replaceAll("_", " ")}</span></div><p className="mt-3 font-semibold">{campaign.headline}</p><p className="mt-2 whitespace-pre-wrap text-slate-700">{campaign.body_text}</p>{campaign.footer_text && <p className="mt-2 text-sm text-slate-500">{campaign.footer_text}</p>}<dl className="mt-5 grid gap-3 text-sm sm:grid-cols-2"><div><dt className="text-slate-500">Template</dt><dd>{campaign.message_template_name || "Missing"} · {campaign.message_template_language || "Missing"}</dd></div><div><dt className="text-slate-500">Audience</dt><dd>{campaign.audience_type.replaceAll("_", " ")}</dd></div><div><dt className="text-slate-500">Scheduled</dt><dd>{campaign.scheduled_at ? new Date(campaign.scheduled_at).toLocaleString() : "Not scheduled"}</dd></div><div><dt className="text-slate-500">Created</dt><dd>{new Date(campaign.created_at).toLocaleString()}</dd></div></dl></div>{campaign.flyer_url ? <img src={campaign.flyer_url} alt="Campaign flyer" className="aspect-square w-full rounded-xl object-cover"/> : <div className="flex aspect-square items-center justify-center rounded-xl bg-slate-100 text-sm text-slate-400">No flyer attached</div>}</section>
    {campaign.coupon && <section className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="font-bold">Coupon {campaign.coupon.code}</h2><p className="mt-1 text-sm text-slate-600">{campaign.coupon.discount_type === "percentage" ? `${campaign.coupon.discount_value}%` : `$${campaign.coupon.discount_value}`} off · {campaign.coupon.redemption_count}{campaign.coupon.redemption_limit ? ` / ${campaign.coupon.redemption_limit}` : ""} redeemed</p><p className="text-xs text-slate-500">{campaign.coupon.expires_at ? `Expires ${new Date(campaign.coupon.expires_at).toLocaleString()}` : "No expiration"} · {campaign.coupon.is_active ? "Active" : "Inactive"}</p></div><div className="flex gap-2"><button disabled={pending || !campaign.coupon.is_active} onClick={()=>act(()=>redeemCoupon(campaign.coupon!.id, {}))} className="rounded-lg border px-3 py-2 text-sm">Redeem manually</button><button disabled={pending || !campaign.coupon.is_active} onClick={()=>act(()=>deactivateCoupon(campaign.coupon!.id), "Deactivate this coupon? Redemption history will be preserved.")} className="rounded-lg border border-red-200 px-3 py-2 text-sm text-red-700">Deactivate</button></div></div></section>}
    <section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-bold">Delivery summary</h2><div className="mt-4 grid grid-cols-3 gap-3 sm:grid-cols-5 lg:grid-cols-8">{["pending","submitted","sent","delivered","read","replied","failed","skipped"].map(status=><div key={status} className="rounded-xl bg-slate-50 p-3 text-center"><b className="block text-xl">{counts[status] || 0}</b><span className="text-xs capitalize text-slate-500">{status}</span></div>)}</div></section>
    {(campaign.status === "draft" || campaign.status === "scheduled") && <section className="rounded-2xl border border-amber-200 bg-amber-50 p-5"><h2 className="font-bold">Audience preview & delivery</h2><p className="mt-1 text-sm">Consent and activity are checked again when recipients are prepared and immediately before each send.</p><div className="mt-4 flex flex-wrap gap-2"><button disabled={pending} onClick={()=>start(async()=>{const r=await previewAudience(campaign.id); if(r.ok)setPreview(r.data as AudiencePreview); else setError(r.error)})} className="rounded-lg border border-slate-300 bg-white px-4 py-2">Preview audience</button><button disabled={pending} onClick={()=>act(()=>sendPromotion(campaign.id), "Send one individual WhatsApp template message to every eligible recipient now?")} className="rounded-lg bg-emerald-600 px-4 py-2 font-semibold text-white">Send now</button><input value={schedule} onChange={e=>setSchedule(e.target.value)} type="datetime-local" className="rounded-lg border border-slate-300 px-3 py-2"/><button disabled={pending || !schedule} onClick={()=>act(()=>schedulePromotion(campaign.id, schedule))} className="rounded-lg bg-slate-900 px-4 py-2 text-white">Schedule</button><button disabled={pending} onClick={()=>act(()=>cancelPromotion(campaign.id), "Cancel this campaign?")} className="rounded-lg border border-red-200 px-4 py-2 text-red-700">Cancel</button></div>{preview && <div className="mt-4 rounded-xl bg-white p-4"><p className="font-semibold">{preview.eligible_count} eligible · {preview.excluded_count} excluded</p><p className="mt-1 text-xs text-slate-500">{Object.entries(preview.exclusion_reasons).map(([reason,count])=>`${reason.replaceAll("_", " ")}: ${count}`).join(" · ") || "No exclusions"}</p><div className="mt-3 flex flex-wrap gap-2">{preview.preview_rows.slice(0,10).map(row=><span key={row.client_id} className="rounded-full bg-slate-100 px-3 py-1 text-xs">{row.name || row.phone}</span>)}</div></div>}</section>}
    <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="p-5"><h2 className="font-bold">Recipients</h2></div>{!campaign.recipients?.length ? <p className="border-t p-8 text-center text-sm text-slate-500">Recipients are snapshotted when sending begins.</p> : <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-5 py-3">Client</th><th>Status</th><th>Consent snapshot</th><th>Delivery</th><th>Failure</th></tr></thead><tbody>{campaign.recipients.map(r=><tr key={r.id} className="border-t"><td className="px-5 py-3"><b>{r.client_name || "Client"}</b><span className="block text-xs text-slate-500">{r.phone}</span></td><td className="capitalize">{r.status}</td><td>{r.consent_source || "Recorded"}<span className="block text-xs text-slate-500">{r.consent_at ? new Date(r.consent_at).toLocaleDateString() : "No timestamp"}</span></td><td className="text-xs">{r.read_at ? `Read ${new Date(r.read_at).toLocaleString()}` : r.delivered_at ? `Delivered ${new Date(r.delivered_at).toLocaleString()}` : r.sent_at ? `Sent ${new Date(r.sent_at).toLocaleString()}` : "—"}</td><td className="max-w-xs text-xs text-red-700">{r.failure_message || "—"}</td></tr>)}</tbody></table></div>}</section>
  </div>;
}
