"use client";
/* eslint-disable @next/next/no-img-element -- newly uploaded local media is intentionally previewed directly */

import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { createPromotion } from "@/app/promotions/actions";
import type { DashboardClient, ServiceOption } from "@/lib/dashboard-types";

export function PromotionForm({ clients, services }: { clients: DashboardClient[]; services: ServiceOption[] }) {
  const router = useRouter(); const [pending, start] = useTransition(); const [error, setError] = useState("");
  const [audience, setAudience] = useState("all_opted_in"); const [couponType, setCouponType] = useState("none");
  const [selected, setSelected] = useState<number[]>([]); const [serviceIds, setServiceIds] = useState<number[]>([]); const [flyerUrl, setFlyerUrl] = useState("");
  async function upload(file: File) {
    setError(""); const base = (process.env.NEXT_PUBLIC_API_BASE_URL || "http://localhost:8000").replace(/\/$/, "");
    const response = await fetch(`${base}/dashboard/promotions/media?filename=${encodeURIComponent(file.name)}`, { method: "POST", headers: { "Content-Type": file.type }, body: file });
    if (!response.ok) { const body = await response.json().catch(()=>null); setError(body?.detail || "Flyer upload failed"); return; }
    const data = await response.json(); setFlyerUrl(`${base}${data.url}`);
  }
  function submit(form: FormData) {
    setError(""); let audience_config: Record<string, unknown> | null = null;
    if (audience === "selected_clients") audience_config = { client_ids: selected };
    if (audience === "service_history") audience_config = { service_ids: serviceIds };
    if (audience === "inactive_days") audience_config = { days: Number(form.get("inactive_days")) };
    if (audience === "birthday_month") audience_config = { month: new Date().getMonth() + 1 };
    const discount = Number(form.get("discount_value"));
    const coupon = couponType === "none" ? null : { code: form.get("coupon_code"), discount_type: couponType, discount_value: discount, service_id: form.get("coupon_service_id") ? Number(form.get("coupon_service_id")) : null, starts_at: form.get("starts_at") || null, expires_at: form.get("expires_at") || null, redemption_limit: form.get("redemption_limit") ? Number(form.get("redemption_limit")) : null };
    const payload = { name: form.get("name"), headline: form.get("headline") || null, body_text: form.get("body_text"), footer_text: form.get("footer_text") || null, message_template_name: form.get("template_name"), message_template_language: form.get("template_language"), audience_type: audience, audience_config, flyer_url: flyerUrl || null, coupon };
    start(async () => { const result = await createPromotion(payload); if (!result.ok) setError(result.error); else router.push(`/promotions/${(result.data as {id:number}).id}`); });
  }
  const input = "mt-1 w-full rounded-lg border border-slate-300 px-3 py-2";
  return <form action={submit} className="space-y-5">
    {error && <div className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</div>}
    <section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-bold">1. Campaign</h2><div className="mt-4 grid gap-4 sm:grid-cols-2"><label>Campaign name<input required name="name" className={input}/></label><label>Headline<input name="headline" className={input}/></label><label className="sm:col-span-2">Message body<textarea required name="body_text" rows={4} className={input}/></label><label>Footer (optional)<input name="footer_text" className={input}/></label><span/><label>WhatsApp template name<input required name="template_name" className={input}/></label><label>Template language<input required name="template_language" defaultValue="en_US" className={input}/></label></div><p className="mt-3 text-xs text-amber-700">The template must already be approved in WhatsApp Manager. Body variables are sent in this order: client name, headline, offer, coupon code, expiration date, business name.</p></section>
    <section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-bold">2. Offer</h2><select value={couponType} onChange={(e)=>setCouponType(e.target.value)} className={`${input} max-w-sm`}><option value="none">No coupon</option><option value="percentage">Percentage discount</option><option value="fixed_amount">Fixed-dollar discount</option></select>{couponType !== "none" && <div className="mt-4 grid gap-4 sm:grid-cols-3"><label>Coupon code<input required name="coupon_code" placeholder={couponType === "percentage" ? "THREAD20" : "SAVE5"} className={input}/></label><label>Discount value<input required min="0.01" max={couponType === "percentage" ? 100 : undefined} step="0.01" type="number" name="discount_value" className={input}/></label><label>Service restriction<select name="coupon_service_id" className={input}><option value="">All services</option>{services.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Start date<input type="datetime-local" name="starts_at" className={input}/></label><label>Expiration date<input type="datetime-local" name="expires_at" className={input}/></label><label>Redemption limit<input min="1" type="number" name="redemption_limit" className={input}/></label></div>}</section>
    <section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-bold">3. Flyer</h2><p className="mt-1 text-sm text-slate-500">Optional JPEG, PNG, or WebP, up to 5 MB. Production sends require a publicly reachable media URL.</p><input className="mt-3" type="file" accept="image/jpeg,image/png,image/webp" onChange={(e)=>{const file=e.target.files?.[0]; if(file) void upload(file)}}/>{flyerUrl && <div className="mt-3 flex items-center gap-3"><img src={flyerUrl} alt="Flyer preview" className="h-28 w-28 rounded-xl object-cover"/><button type="button" onClick={()=>setFlyerUrl("")} className="text-sm text-red-600">Remove</button></div>}</section>
    <section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-bold">4. Audience</h2><p className="mt-1 text-sm text-emerald-700">Only active clients with explicit marketing consent can be eligible.</p><select value={audience} onChange={e=>setAudience(e.target.value)} className={`${input} max-w-md`}><option value="all_opted_in">All opted-in clients</option><option value="selected_clients">Selected clients</option><option value="service_history">Previous customers of services</option><option value="inactive_days">Inactive clients</option><option value="birthday_month">Birthday this month</option><option value="never_booked">Never booked</option></select>{audience === "inactive_days" && <select name="inactive_days" className={`${input} max-w-xs`}><option value="30">30 days</option><option value="60">60 days</option><option value="90">90 days</option></select>}{audience === "selected_clients" && <div className="mt-3 grid max-h-64 gap-2 overflow-auto sm:grid-cols-2">{clients.map(c=><label key={c.id} className="rounded-lg border p-2"><input type="checkbox" checked={selected.includes(c.id)} onChange={e=>setSelected(v=>e.target.checked?[...v,c.id]:v.filter(id=>id!==c.id))}/> <span className="ml-2">{c.name}</span><span className="block pl-6 text-xs text-slate-500">{c.marketing_opt_in ? "Consented" : "Ineligible — no consent"}</span></label>)}</div>}{audience === "service_history" && <div className="mt-3 grid gap-2 sm:grid-cols-2">{services.map(s=><label key={s.id} className="rounded-lg border p-2"><input type="checkbox" checked={serviceIds.includes(s.id)} onChange={e=>setServiceIds(v=>e.target.checked?[...v,s.id]:v.filter(id=>id!==s.id))}/> <span className="ml-2">{s.name}</span></label>)}</div>}</section>
    <section className="rounded-2xl border border-amber-200 bg-amber-50 p-5"><h2 className="font-bold">5–6. Preview & delivery</h2><p className="mt-1 text-sm">Saving creates a draft only. On the next screen you must preview the eligible audience, then explicitly confirm Send now or schedule a future time.</p><button disabled={pending} className="mt-4 rounded-lg bg-slate-900 px-5 py-2.5 font-semibold text-white disabled:opacity-50">{pending ? "Saving…" : "Save draft and continue"}</button></section>
  </form>;
}
